In [1]:
import pandas as pd
import numpy as np

In [8]:
df_partidas = pd.read_csv('partidas.csv').drop(columns=['Unnamed: 0'])
df_partidas['DateTime UTC'] = pd.to_datetime(df_partidas['DateTime UTC'], errors='coerce')
for i in [1,2]: df_partidas[f'Team{i}RiftHeralds'] = df_partidas[f'Team{i}RiftHeralds'].fillna(0.0)

df = pd.DataFrame()
for i,partida in df_partidas.iterrows():
    # Verificar se existem partidas anteriores dos 2 times na liga
    df_retro_1 = df_partidas[(df_partidas['DateTime UTC']<partida['DateTime UTC'])&
                             ((df_partidas['Team1']==partida['Team1'])|
                              (df_partidas['Team2']==partida['Team1']))]
    df_retro_2 = df_partidas[(df_partidas['DateTime UTC']<partida['DateTime UTC'])&
                             ((df_partidas['Team1']==partida['Team2'])|
                              (df_partidas['Team2']==partida['Team2']))]
    if len(df_retro_1) == 0 or len(df_retro_1) == 0: continue
    dados_retro = {'winrate1':[],'winrate2':[],'Dragons_avg1':[],'Dragons_avg2':[],'Barons_avg1':[],
                   'Barons_avg2':[],'Towers_avg1':[],'Towers_avg2':[],'Kills_avg1':[],'Kills_avg2':[],
                   'Inhib_avg1':[],'Inhib_avg2':[],'Heralds_avg1':[],'Heralds_avg2':[],'Gold_min1':[],
                   'Gold_min2':[]}
    # Para cada partida anterior encontrada do time 1, verificar se esse time era o 1 ou o 2 
    # e aquisitar as estatisticas do respectivo time
    for j,partida_1 in df_retro_1.iterrows():
        if partida_1['Team1'] == partida['Team1']: team = '1'
        else: team = '2'
        if partida_1['WinTeam'] == partida['Team1']: dados_retro['winrate1'].append(1)
        else: dados_retro['winrate1'].append(0)
        dados_retro['Dragons_avg1'].append(partida_1[f'Team{team}Dragons'])
        dados_retro['Barons_avg1'].append(partida_1[f'Team{team}Barons'])
        dados_retro['Towers_avg1'].append(partida_1[f'Team{team}Towers'])
        dados_retro['Kills_avg1'].append(partida_1[f'Team{team}Kills'])
        dados_retro['Inhib_avg1'].append(partida_1[f'Team{team}Inhibitors'])
        dados_retro['Heralds_avg1'].append(partida_1[f'Team{team}RiftHeralds'])
        dados_retro['Gold_min1'].append(partida_1[f'Team{team}Gold']/(partida_1['Gamelength Number']))
    for j,partida_2 in df_retro_2.iterrows():
        if partida_2['Team1'] == partida['Team2']: team = '1'
        else: team = '2'
        if partida_2['WinTeam'] == partida['Team2']: dados_retro['winrate2'].append(1)
        else: dados_retro['winrate2'].append(0)
        dados_retro['Dragons_avg2'].append(partida_1[f'Team{team}Dragons'])
        dados_retro['Barons_avg2'].append(partida_1[f'Team{team}Barons'])
        dados_retro['Towers_avg2'].append(partida_1[f'Team{team}Towers'])
        dados_retro['Kills_avg2'].append(partida_1[f'Team{team}Kills'])
        dados_retro['Inhib_avg2'].append(partida_1[f'Team{team}Inhibitors'])
        dados_retro['Heralds_avg2'].append(partida_1[f'Team{team}RiftHeralds'])
        dados_retro['Gold_min2'].append(partida_1[f'Team{team}Gold']/(partida_1['Gamelength Number']))
    for chave, lista in dados_retro.items():
        dados_retro[chave] = np.mean(lista)
    dados_retro = pd.DataFrame([dados_retro])
    df = pd.concat([df,dados_retro], ignore_index=True)

c:\Users\Samsung\anaconda3\envs\myenv\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\Samsung\anaconda3\envs\myenv\lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
c:\Users\Samsung\anaconda3\envs\myenv\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\Samsung\anaconda3\envs\myenv\lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
c:\Users\Samsung\anaconda3\envs\myenv\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\Samsung\anaconda3\envs\myenv\lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

In [9]:
df

,winrate1,winrate2,Dragons_avg1,Dragons_avg2,Barons_avg1,Barons_avg2,Towers_avg1,Towers_avg2,Kills_avg1,Kills_avg2,Inhib_avg1,Inhib_avg2,Heralds_avg1,Heralds_avg2,Gold_min1,Gold_min2
0,1.000000,0.0,3.000000,1.0,1.000000,0.0,7.000000,7.0,24.00,18.0,1.0,1.0,1.000000,0.0,2042.229008,1900.091603
1,1.000000,1.0,3.000000,0.0,2.000000,0.0,11.000000,0.0,17.00,1.0,3.0,0.0,1.000000,0.0,2142.123040,1513.570567
2,1.000000,0.0,2.000000,2.0,1.000000,0.0,9.000000,3.0,14.00,10.0,2.0,0.0,1.000000,0.0,1947.668571,1771.062857
3,1.000000,0.0,4.000000,2.0,2.000000,1.0,9.000000,4.0,20.00,9.0,1.0,0.0,1.000000,0.0,1957.316456,1680.177215
4,0.000000,0.0,2.000000,3.0,0.000000,2.0,3.000000,9.0,4.00,16.0,0.0,1.0,0.000000,1.0,1611.177319,1982.739068
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,0.500000,1.0,2.750000,4.0,0.500000,1.0,5.000000,9.0,12.25,18.0,1.0,2.0,0.750000,1.0,1856.048749,2031.438395
84,1.000000,0.4,2.800000,1.6,1.000000,0.6,8.200000,4.6,12.80,8.4,1.4,0.4,0.600000,0.6,1931.443048,1774.716511
85,0.000000,1.0,3.000000,3.0,1.000000,1.0,4.000000,8.0,13.00,12.0,0.0,2.0,0.000000,0.0,1751.491634,1778.533286
86,0.800000,0.0,2.600000,3.0,0.800000,0.0,7.600000,9.0,14.40,13.0,1.4,1.0,0.600000,1.0,1887.470348,1868.217780
87,0.833333,0.0,2.833333,2.0,0.833333,1.0,7.666667,2.0,16.00,13.0,1.5,0.0,0.666667,0.0,1901.265773,1700.996295

In [31]:
dados_retro = {'winrate1':[],'winrate2':[],'Dragons_avg1':[],'Dragons_avg2':[],'Barons_avg1':[],
                   'Barons_avg2':[],'Towers_avg1':[],'Towers_avg2':[],'Kills_avg1':[],'Kills_avg2':[],
                   'Inhib_avg1':[],'Inhib_avg2':[],'Heralds_avg1':[],'Heralds_avg2':[],'Gold_min1':[],
                   'Gold_min2':[]}
dados_retro['winrate1'].append(1)
dados_retro['winrate1'] = np.mean(dados_retro['winrate1'])
dados_retro

{'winrate1': 1.0,
 'winrate2': [],
 'Dragons_avg1': [],
 'Dragons_avg2': [],
 'Barons_avg1': [],
 'Barons_avg2': [],
 'Towers_avg1': [],
 'Towers_avg2': [],
 'Kills_avg1': [],
 'Kills_avg2': [],
 'Inhib_avg1': [],
 'Inhib_avg2': [],
 'Heralds_avg1': [],
 'Heralds_avg2': [],
 'Gold_min1': [],
 'Gold_min2': []}